version: '3'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24


services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    restart: always
    volumes:
      - ./src:/app/src
    networks:
      app_net:
        ipv4_address: 172.24.0.2


  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.24.0.3

